version: '3'

services:
 web:
    build: ./nginx
    ports:
        - 80:80
    depends_on:
        - app
    volumes:
        - ./:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app
 app:
    build: ./php
    depends_on:
        - db
    links:
        - db
    volumes:
        - ./:/var/www/html
 db:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root         #ここにroot用のパスワードを記載
      MYSQL_DATABASE: default         #ここにデータベースを記載
      MYSQL_USER: default           #ここにユーザ名を記載
      MYSQL_PASSWORD: password   #ここにユーザ用パスワードを記載
