version: "3"

services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php
    build: ./php
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root #ここにroot用のパスワードを記載
